# Generated by Django 4.0.4 on 2023-01-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuecard',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuecard',
            name='concept',
            field=models.CharField(max_length=100),
        ),
    ]
